services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:
    driver: bridge


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/relaforg/data/mariadb
      o: bind
