services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: unless-stopped
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: unless-stopped
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "root"]
      interval: 5s
      timeout: 3s
      retries: 10

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: unless-stopped
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "echo '' | nc -w 1 localhost 9000"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    container_name: redis
    build: requirements/redis
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  ftp:
    container_name: ftp
    build: requirements/ftp
    restart: unless-stopped
    networks:
      - inception
    env_file: .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html/wordpress

  static_site:
    container_name: static_site
    build: requirements/static_site
    restart: unless-stopped
    networks:
      - inception
    ports:
      - "8080:80"

networks:
  inception:
    driver: bridge


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/relaforg/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/relaforg/data/wordpress
      o: bind
