server {
    listen 8081;

    root /var/www/html;
    index adminer.php;

    location / {
	try_files $uri $uri/ /adminer.php;
    }

    location ~ \.php {
	fastcgi_pass unix:/run/php/php8.2-fpm.sock;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	include fastcgi_params;
    }
}
