ServerName		"Inception FTP server"
ServerType		standalone
DefaultServer		on
Port			21

DefaultRoot		/var/www/html/wordpress

UseIPv6			off

TimeoutNoTransfer	600
TimeoutStalled		600
TimeoutIdle		1200

PassivePorts		21100 21110

<Limit LOGIN>
    AllowUser		ftpuser
    DenyAll
</Limit>
